### PR TITLE
if row 'group' is present, users are added to that group

### PR DESCRIPTION
**Pull request by espenmn**
When the CSV file has a row: group, the user is added to that group.

email,username,fullname,group
jim@email.com,jim,Jim My,TeamA

Will add 'jim' to 'TeamA' group

### CODE REVIEW

**Comment by cekk** [comment]
@espenmn thanks for your help!

Could you update also README and History with your changes?

**Comment by espenmn** [comment]
Done 
Should I remove this pull request and make a new with README and history ?

**Comment by cekk** [comment]
If you prefer, you could also update this one..do what you want

**Comment by cekk** [comment]
@espenmn i've fixed a bit the readme and history, and released a new version on pypi.
Thanks

**Pull request merged**
